image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - restore_and_build
  - deploy

restore_and_build_service:
  stage: restore_and_build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .nuget/packages/
      - AuthService/obj/
      - UserService/obj/
      - CourseManagementService/obj/
  script:
    - dotnet restore edusmartbe.sln --packages .nuget/packages
    - ls -la .nuget/packages/  # List directory contents to verify packages have been restored
    - |
      services=("AuthService" "UserService" "CourseManagementService")
      for service in "${services[@]}"; do
        if git diff --name-only HEAD HEAD~1 | grep -q "${service}/"; then
          echo "Building ${service}..."
          dotnet build ${service}/${service}.csproj --configuration Release --no-restore
        else
          echo "No changes in ${service}, skipping build."
        fi
      done
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"' # Unnecessary to build projects when pushing to main branch
      changes:
        - 'AuthService/**/*'
        - 'UserService/**/*'
        - 'CourseManagementService/**/*'
  # Cần cache thư mục .nuget/packages/ để giảm thời gian restore packages
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .nuget/packages/

deploy_services:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:8.0
  environment: production
  before_script:
    - apt-get update && apt-get install -y openssh-client  # Cài đặt SSH client bằng apt-get
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "Pulling latest code from the repository"
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_SERVER_IP "cd $PATH_TO_PROJECT && eval \"\$(ssh-agent -s)\" && ssh-add /root/.ssh/id_rsa_gitlab && git fetch --prune origin && git reset --hard origin/main && git clean -fd && git gc --prune=now && git pull origin main"
    - |
      services=("authservice" "userservice" "coursemanagementservice")
      for service in "${services[@]}"; do
        # Kiểm tra xem có thay đổi nào trong service đó hoặc trong docker-compose.yml hoặc .gitlab-ci.yml không
        if git diff --name-only HEAD HEAD~1 | grep -qiE "^${service}/|^docker-compose.yml|.gitlab-ci.yml"; then
          echo "Deploying ${service} to production server"
          "docker-compose build $service && docker-compose up -d --no-deps $service"
          echo "${service} deployed successfully"
        else
          echo "No changes detected for ${service}. Skipping deployment."
        fi
      done
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - '.gitlab-ci.yml'
        - 'docker-compose.yml'
        - 'AuthService/**/*'
        - 'UserService/**/*'
        - 'CourseManagementService/**/*'