version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Cổng cho AMQP
      - "15672:15672"  # Cổng quản lý giao diện web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "7150:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - microservices-network

  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "7151:80"
      - "10001:10001" # Cổng cho gRPC
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - microservices-network

  coursemanagementservice:
    build:
      context: ./CourseManagementService
      dockerfile: Dockerfile
    container_name: courseservice
    ports:
      - "7152:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - microservices-network
   

networks:
  microservices-network:
    driver: bridge

volumes:
  rabbitmq_data:
