version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Cổng cho AMQP
      - "15672:15672"  # Cổng quản lý giao diện web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "7150:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - microservices-network

  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "7151:80"
      - "10001:10001" # Cổng cho gRPC
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - microservices-network

  coursemanagementservice:
    build:
      context: ./CourseManagementService
      dockerfile: Dockerfile
    container_name: courseservice
    ports:
      - "7152:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - microservices-network
  
  paymentservice:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    container_name: paymentservice
    ports:
      - "7153:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - microservices-network

  mediaservice:
    build:
      context: ./MediaService
      dockerfile: Dockerfile
    container_name: mediaservice
    ports:
      - "7154:7154"
    environment:
      - NODE_ENV=production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - microservices-network

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pbl6duter
      POSTGRES_PASSWORD: Edusmartk21
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data:
