// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaymentService.Databases;

#nullable disable

namespace PaymentService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241208134624_CreateUploadHistoryTable")]
    partial class CreateUploadHistoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentService.Databases.Schemas.Bank", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Bin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("Bank Identification Number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LogoURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Banks", (string)null);
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsAdminAccount")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("IsPrimary", "IsAdminAccount");

                    b.ToTable("BankAccounts", (string)null);
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.ExtendStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BoughtAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasComment("The price of the storage at the time of purchase");

                    b.Property<long>("StorageAmount")
                        .HasColumnType("bigint")
                        .HasComment("The amount of storage that is bought");

                    b.Property<int>("StorageInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageInfoId");

                    b.ToTable("ExtendStorages", (string)null);
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedInformation")
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.StorageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("MaximumStorage")
                        .HasColumnType("bigint");

                    b.Property<long>("UsedStorage")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StorageInfos", (string)null);
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.TeacherEarning", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalWithdrawn")
                        .HasColumnType("numeric");

                    b.HasKey("UserId");

                    b.ToTable("TeacherEarnings", (string)null);
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.UploadHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaStorageProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StorageAmount")
                        .HasColumnType("bigint");

                    b.Property<int>("StorageInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageInfoId");

                    b.ToTable("UploadHistories", (string)null);
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("UserId");

                    b.ToTable("WithdrawalRequests", (string)null);
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.BankAccount", b =>
                {
                    b.HasOne("PaymentService.Databases.Schemas.Bank", "Bank")
                        .WithMany("BankAccounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.ExtendStorage", b =>
                {
                    b.HasOne("PaymentService.Databases.Schemas.StorageInfo", "StorageInfo")
                        .WithMany("ExtendStorages")
                        .HasForeignKey("StorageInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StorageInfo");
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.UploadHistory", b =>
                {
                    b.HasOne("PaymentService.Databases.Schemas.StorageInfo", "StorageInfo")
                        .WithMany("UploadHistories")
                        .HasForeignKey("StorageInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StorageInfo");
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.WithdrawalRequest", b =>
                {
                    b.HasOne("PaymentService.Databases.Schemas.BankAccount", "BankAccount")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PaymentService.Databases.Schemas.TeacherEarning", "TeacherEarning")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("TeacherEarning");
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.Bank", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.BankAccount", b =>
                {
                    b.Navigation("WithdrawalRequests");
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.StorageInfo", b =>
                {
                    b.Navigation("ExtendStorages");

                    b.Navigation("UploadHistories");
                });

            modelBuilder.Entity("PaymentService.Databases.Schemas.TeacherEarning", b =>
                {
                    b.Navigation("WithdrawalRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
