syntax = "proto3";
option csharp_namespace = "PaymentService.GrpcServices";
import "google/protobuf/timestamp.proto";

service Course {
    rpc EnrollCourse(CourseEnrollmentRequest) returns (CourseEnrollmentResponse);
    rpc GetInfoCourseByIds(GetInfoCourseByIdsRequest) returns (GetInfoCourseByIdsResponse);
}

message CourseEnrollmentRequest {
    string courseId = 1;
    int32 studentId = 2;
    google.protobuf.Timestamp enrollmentDate = 3;
}

message CourseEnrollmentResponse {
    string enrollmentId = 1;
    string message = 2;
    bool isSuccess = 3;
}

message GetInfoCourseByIdsRequest {
    repeated RevenueCourseGrpc revenueCourses = 1;
}

message GetInfoCourseByIdsResponse {
    repeated RevenueCourseGrpc revenueCourses = 1;
    string message = 2;
    bool isSuccess = 3;
}

message RevenueCourseGrpc {
    double amount = 1;
    string currency = 2;
    string courseName = 3;
    RelatedInfoGrpc relatedInfo = 4;
}

message RelatedInfoGrpc {
    string courseId = 1;
    int32 teacherId = 2;
}