syntax = "proto3";
option csharp_namespace = "CourseManagementService.GrpcServices";
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

service Course {
    rpc GetCoursesByIds(GetCoursesByIdsRequest) returns (GetCoursesByIdsResponse);
    rpc EnrollCourse(CourseEnrollmentRequest) returns (CourseEnrollmentResponse);
    rpc GetInfoCourseByIds(GetInfoCourseByIdsRequest) returns (GetInfoCourseByIdsResponse);
    rpc GetMonthlyDiscussions(google.protobuf.Empty) returns (MonthlyDataCourseResponse);
    rpc CheckStudentCompletedCourse(CheckStudentCompletedCourseRequest) returns (CheckStudentCompletedCourseResponse);
}

message SimpleCourseInfo {
    string id = 1;
    string name = 2;
}

message GetCoursesByIdsRequest {
    repeated string courseIds = 1;
}

message GetCoursesByIdsResponse {
    repeated SimpleCourseInfo courses = 1;
    string message = 2;
    bool isSuccess = 3;
}

message CourseEnrollmentRequest {
    string courseId = 1;
    int32 studentId = 2;
    google.protobuf.Timestamp enrollmentDate = 3;
}

message CourseEnrollmentResponse {
    string enrollmentId = 1;
    string message = 2;
    bool isSuccess = 3;
}

message GetInfoCourseByIdsRequest {
    repeated RevenueCourseGrpc revenueCourses = 1;
}

message GetInfoCourseByIdsResponse {
    repeated RevenueCourseGrpc revenueCourses = 1;
    string message = 2;
    bool isSuccess = 3;
}

message RevenueCourseGrpc {
    double amount = 1;
    string currency = 2;
    string courseName = 3;
    RelatedInfoGrpc relatedInfo = 4;
}

message RelatedInfoGrpc {
    string courseId = 1;
    int32 teacherId = 2;
}

message MonthlyDataCourseResponse {
    repeated MonthlyDataCourse monthlyDataCourse = 1;
    string message = 2;
    bool isSuccess = 3;
}

message MonthlyDataCourse {
    int32 month = 1;
    int64 amount = 2;
}

message CheckStudentCompletedCourseRequest {
    int32 studentId = 1;
    string courseId = 2;
}

message CheckStudentCompletedCourseResponse {
    bool isCompleted = 1;
    string studentName = 2;
    string courseName = 3;
    string teacherName = 4;
    string message = 5;
    bool isSuccess = 6;
}