syntax = "proto3";
option csharp_namespace = "CourseManagementService.GrpcServices";
import "google/protobuf/empty.proto";

service Payment {
    rpc GetAdminBankAccount(google.protobuf.Empty) returns (BankAccountResponse);
    rpc CreateCoursePaymentTransaction(CoursePaymentTransactionRequest) returns (CoursePaymentTransactionResponse);
    rpc GetExchangeRate(google.protobuf.Empty) returns (ExchangeRate);
    rpc GetCurrentStoringAmount(UserInfo) returns (StorageInfoResponse);
    rpc GetAchievementURLInCompletedCourses(CompletedCourses) returns (CompletedCourses);
}

enum Currency {
    UNKNOWN = 0;
    USD = 1;
    VND = 2;
}

message UserInfo {
    int32 id = 1;
}

message ExchangeRate {
    string from_currency = 1; // Tên tiền tệ gốc, ví dụ: USD
    string to_currency = 2;   // Tên tiền tệ đích, ví dụ: VND
    double rate = 3;          // Tỷ giá, ví dụ: 25397
}

message BankAccountResponse {
    string bankBin = 1;
    string bankName = 2;
    string accountNumber = 3;
    string accountName = 4;
    bool isSuccess = 5;
}

message CoursePaymentTransactionRequest {
    string code = 1;
    int32 userId = 2;
    string username = 3;
    string fullName = 4;
    string email = 5;
    double amount = 6;
    int32 receiverId = 7;
    Currency currency = 8;
    string relatedInfo = 9;
}

message CoursePaymentTransactionResponse {
    string transactionId = 1;
    bool isSuccess = 2;
    ExchangeRate ExchangeRate = 3;
}

message StorageInfoResponse {
    int64 maximumStorage = 1;
    int64 usedStorage = 2;
    string message = 3;
    bool isSuccess = 4;
}

message CompletedCourses {
    int32 userId = 1;
    repeated CompletedCourseInfo completedCourseInfo = 2;
    string message = 3;
    bool isSuccess = 4;
}

message CompletedCourseInfo {
    string id = 1;
    string name = 2;
    string achievementURL = 3;
}