syntax = "proto3";
option csharp_namespace = "CourseManagementService.GrpcServices";
import "google/protobuf/wrappers.proto";

service User {
    rpc GetUserInfo (UserRequest) returns (UserResponse);
    rpc CheckUserExist (UserRequest) returns (CheckUserExistResponse);
    rpc GetListOfTeachers (UsersRequest) returns (ListOfUsersResponse);
    rpc GetTeachersByName(UserRequest) returns (ListOfUsersResponse);
}

// Dùng để lấy thông tin user theo id
message UserRequest {
    int32 id = 1;
    string name = 2;
}

// Dùng để lấy danh sách user theo mảng id
message UsersRequest {
    repeated int32 ids = 1; // Truyền vào mảng các id
}

message SimpleUserResponse {
    int32 id = 1;
    string userName = 2;
    string fullName = 3;
    google.protobuf.StringValue avatarURL = 4;
    google.protobuf.StringValue email = 5;
}

message UserResponse {
    int32 id = 1;
    string userName = 2;
    string firstName = 3;
    string lastName = 4;
    string email = 5;
}

message ListOfUsersResponse {
    repeated SimpleUserResponse users = 1;
}

message CheckUserExistResponse {
    bool isExist = 1;
}